steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/library-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/library-api:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/library-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/library-api:latest'

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=kubernetes/deployment.yaml'
      - '--location=us-central1'
      - '--cluster=library-cluster'
      - '--image=gcr.io/$PROJECT_ID/library-api:$COMMIT_SHA'

images:
  - 'gcr.io/$PROJECT_ID/library-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/library-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'